name: CI/CD
on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  FUNCTIONS_NAME: sugatan_hyros
  TOPIC_ID: hyros
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Cloud Functions
        run: >-
          gcloud functions deploy ${{ env.FUNCTIONS_NAME }}
          --entry-point=main
          --timeout=530
          --project=${{ secrets.PROJECT_ID }}
          --memory=1024MB
          --runtime=python39
          --trigger-http
          --service-account=${{ secrets.GCP_SA }}
          --set-env-vars=API_KEY=${{ secrets.API_KEY }}
